const ArrayUnits = [ 
  "INTS > REGIAO SACA",
  "AMA Especialidades Vila Constância - Dr. Vicente Octavio Guida",
  "AMA/UBS Jardim Miriam I - Manoel Soares de Oliveira",
  "AMA/UBS Vila Império I",
  "AMA/UBS Vila Joaniza - João Yunes",
  "AMA/UBS Vila Missionária",
  "APD Santo Amaro",
  "CAPS AD II - Cidade Ademar",
  "CAPS Adulto II - Cidade Ademar",
  "CAPS III Adulto Largo 13",
  "CAPS Infanto Juvenil II Cidade Ademar",
  "CAPS Infanto Juvenil II Santo Amaro",
  "CEO ll LRPD - Dr. Humberto Nastari",
  "CER III - Cidade Ademar",
  "Comunicação",
  "Coordenação",
  "Hospital das Clínicas",
  "Hospital Dia Cidade Ademar",
  "Hospital Dia Santo Amaro",
  "Serviço de Assistência Domiciliar - Cidade Ademar",
  "SRT  Santo Amaro III",
  "SRT Cidade Ademar I",
  "SRT Cidade Ademar II",
  "SRT Santo Amaro I",
  "SRT Santo Amaro II",
  "UBS Campo Grande",
  "UBS Chácara Santo Antônio - Dr. Marcílio de Arruda Penteado",
  "UBS Integral Jardim Miriam II",
  "UBS Jardim Aeroporto - Dr. Massaki Udihara",
  "UBS Jardim Umuarama",
  "UBS Parque Dorotéia",
  "UBS Parque dos Búfalos",
  "UBS Santo Amaro - Dr. Sergio Villaca Braga",
  "UBS Vila Arriete - Dr. Decio Pcheco Pedroso",
  "UBS Vila Constância - Dr. Vicente Octavio Guida",
  "UBS/ESF Cidade Júlia",
  "UBS/ESF Jardim Apurá",
  "UBS/ESF Jardim Niterói",
  "UBS/ESF Jardim Novo Pantanal",
  "UBS/ESF Jardim São Carlos",
  "UBS/ESF Jardim Selma",
  "UBS/ESF Laranjeiras",
  "UBS/ESF Mar Paulista",
  "UBS/ESF Mata Virgem",
  "UBS/ESF São Jorge",
  "UBS/ESF Vila Aparecida",
  "UBS/ESF Vila Guacuri - Cicero Sergio Cavalcante",
  "UBS/ESF Vila Império II - Dra. Gilda Tera Tahira",
  "UPA 24hs Pq. Doroteia",
  "UPA Pedreira - Dr. Cesar Antunes da Rocha",
  "UPA Santo Amaro - Dr. Jose Sylvio de Camargo",
  "URSI - Cidade Ademar"
]
// length : 52
// [[Prototype]] : Array(0)